"""Initial schema

Revision ID: 93b24c0cf339
Revises: 
Create Date: 2026-06-04 22:55:29.889980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b24c0cf339'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_queries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('sql_query', sa.Text(), nullable=True),
    sa.Column('results_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cached_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cached_queries_query_hash'), ['query_hash'], unique=True)

    op.create_table('locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('area_code', sa.String(length=20), nullable=True),
    sa.Column('camera_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('violation_fines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('violation_type', sa.String(length=50), nullable=False),
    sa.Column('base_amount', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.Column('effective_to', sa.DateTime(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violation_fines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violation_fines_violation_type'), ['violation_type'], unique=False)

    op.create_table('violations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_number', sa.String(length=30), nullable=False),
    sa.Column('owner_name', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('violation_type', sa.String(length=20), nullable=False),
    sa.Column('fine_amount', sa.Integer(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('image_path', sa.String(length=200), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_violations_date_time'), ['date_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_violations_vehicle_number'), ['vehicle_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_violations_violation_type'), ['violation_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violations_violation_type'))
        batch_op.drop_index(batch_op.f('ix_violations_vehicle_number'))
        batch_op.drop_index(batch_op.f('ix_violations_date_time'))

    op.drop_table('violations')
    with op.batch_alter_table('violation_fines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violation_fines_violation_type'))

    op.drop_table('violation_fines')
    op.drop_table('locations')
    with op.batch_alter_table('cached_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cached_queries_query_hash'))

    op.drop_table('cached_queries')
    # ### end Alembic commands ###
